version: '3.8'
services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=mediumclone
      - POSTGRES_DB=mediumclone
    ports:
      - 5432:5432